FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["Mince\\src\\Forms\\Button.bf", "Mince\\src\\Forms\\Window.bf", "Mince\\src\\Core\\SDL2.bf", "Mince\\src\\Forms\\CheckBox.bf", "Mince\\src\\Core\\KeyEvent.bf", "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Event.bf", "Mince\\src\\Forms\\Panel.bf", "Mince\\src\\Forms\\ScrollBarHoriz.bf", "Mince\\src\\Core\\Control.bf", "Mince\\src\\Core\\Frame.bf", "MinceTest\\src\\Form.bf"]

[MainWindow]
X = 4127
Y = 66
Width = 1224
Height = 905
ShowKind = "Normal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 280.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ScrollBarHoriz.bf"
TabWidth = 137.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\ScrollBarHoriz.bf"
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Event.bf"
TabWidth = 86.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Event.bf"
CursorPos = 3848
VertPos = 2625.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Window.bf"
TabWidth = 102.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Window.bf"
CursorPos = 2461
VertPos = 1260.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Control.bf"
TabWidth = 98.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\Control.bf"
CursorPos = 1834
VertPos = 975.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Frame.bf"
TabWidth = 91.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\Frame.bf"
CursorPos = 300
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Panel.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Panel.bf"
CursorPos = 1469
VertPos = 315.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Form.bf"
TabWidth = 75.0
Type = "SourceViewPanel"
FilePath = "MinceTest\\src\\Form.bf"
CursorPos = 424
ProjectName = "MinceTest"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Button.bf"
TabWidth = 82.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Button.bf"
CursorPos = 1097
VertPos = 536.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CheckBox.bf"
TabWidth = 100.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\CheckBox.bf"
CursorPos = 842
VertPos = 405.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "KeyEvent.bf"
TabWidth = 97.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\KeyEvent.bf"
CursorPos = 11461
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SDL2.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\SDL2.bf"
CursorPos = 4036
VertPos = 2385.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 370.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4379562
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5620438
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "Mince\\src\\Forms\\CheckBox.bf"
Line = 45
Column = 1

[[Breakpoints]]
File = "Mince\\src\\Forms\\Button.bf"
Line = 53
Column = 3

[[Breakpoints]]
File = "Mince\\src\\Forms\\Button.bf"
Line = 44
Column = 3
