FileVersion = 1
Projects = {MinceTest = {Path = "MinceTest"}, Mince = {Path = "Mince"}}

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
