FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["MinceTest\\src\\Form.bf", "Mince\\src\\Forms\\ListBox.bf", "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Collections\\List.bf", "Mince\\src\\Forms\\Button.bf", "Mince\\src\\Core\\Control.bf", "Mince\\src\\Forms\\ListView.bf"]

[MainWindow]
X = 2123
Y = 199
Width = 1405
Height = 905
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 280.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Form.bf"
TabWidth = 85.0
Type = "SourceViewPanel"
FilePath = "MinceTest\\src\\Form.bf"
CursorPos = 3033
VertPos = 1380.0
ProjectName = "MinceTest"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "List.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Collections\\List.bf"
CursorPos = 3167
VertPos = 2565.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Control.bf"
TabWidth = 98.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\Control.bf"
CursorPos = 1628
VertPos = 585.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Button.bf"
TabWidth = 92.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Button.bf"
CursorPos = 1171
VertPos = 540.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ListView.bf"
TabWidth = 91.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\ListView.bf"
CursorPos = 240
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ListBox.bf"
TabWidth = 85.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\ListBox.bf"
CursorPos = 1230
VertPos = 405.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 370.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4379562
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5620438
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"
