FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["MinceTest\\src\\Form.bf", "Mince\\src\\Forms\\CheckBox.bf", "Mince\\src\\Forms\\Button.bf", "Mince\\src\\Forms\\Window.bf", "Mince\\src\\Core\\Control.bf", "Mince\\src\\Core\\Event.bf", "Mince\\src\\Core\\SDL2.bf", "Mince\\src\\Forms\\Theme.bf", "z:\\Development\\Beef\\BeefLibs\\SDL2\\src\\SDL2.bf", "Mince\\src\\Forms\\RadioButton.bf", "Mince\\src\\Forms\\RadioGroup.bf", "Mince\\src\\Core\\KeyEvent.bf", "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Event.bf", "Mince\\src\\Core\\Frame.bf", "Mince\\src\\Forms\\Panel.bf", "Mince\\src\\Forms\\ScrollBarHoriz.bf"]

[MainWindow]
X = 2236
Y = 0
Width = 1224
Height = 905
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 280.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SDL2.bf"
TabWidth = 84.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\Beef\\BeefLibs\\SDL2\\src\\SDL2.bf"
CursorPos = 95929
VertPos = 54810.84
ProjectName = "SDL2"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Theme.bf"
TabWidth = 94.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Theme.bf"
CursorPos = 5327
VertPos = 2726.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RadioGroup.bf"
TabWidth = 116.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\RadioGroup.bf"
CursorPos = 1129
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "RadioButton.bf"
TabWidth = 116.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\RadioButton.bf"
CursorPos = 602
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ScrollBarHoriz.bf"
TabWidth = 127.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\ScrollBarHoriz.bf"
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Event.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Event.bf"
CursorPos = 3848
VertPos = 2625.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Window.bf"
TabWidth = 92.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Window.bf"
CursorPos = 4243
VertPos = 2070.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Control.bf"
TabWidth = 88.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\Control.bf"
CursorPos = 1120
VertPos = 225.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Frame.bf"
TabWidth = 81.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\Frame.bf"
CursorPos = 300
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Panel.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Panel.bf"
CursorPos = 1469
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Form.bf"
TabWidth = 75.0
Type = "SourceViewPanel"
FilePath = "MinceTest\\src\\Form.bf"
CursorPos = 1069
ProjectName = "MinceTest"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Button.bf"
TabWidth = 82.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\Button.bf"
CursorPos = 1897
VertPos = 1001.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CheckBox.bf"
TabWidth = 100.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Forms\\CheckBox.bf"
CursorPos = 2074
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "KeyEvent.bf"
TabWidth = 97.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\KeyEvent.bf"
CursorPos = 11461
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SDL2.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "Mince\\src\\Core\\SDL2.bf"
CursorPos = 5842
VertPos = 3375.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 370.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4379562
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5620438
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"
