FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Forms\\Text.bf", "src\\Core\\Control.bf", "src\\Forms\\Window.bf", "z:\\Development\\MinceTest\\src\\Form.bf", "src\\Forms\\Button.bf", "src\\Core\\SDL2.bf", "src\\Forms\\ScrollBarVert.bf", "src\\Core\\Event.bf", "src\\Core\\Rect.bf", "src\\Forms\\Panel.bf", "src\\Forms\\Theme.bf", "src\\Forms\\ScrollBarHoriz.bf", "src\\Core\\Background.bf", "src\\Core\\Frame.bf", "src\\Core\\Color.bf", "src\\Core\\Point.bf", "src\\Core\\Size.bf", "z:\\Development\\MinceTest\\src\\Program.bf", "z:\\Development\\Beef\\BeefLibs\\SDL2\\src\\SDL2_ttf.bf"]

[MainWindow]
X = 4073
Y = 54
Width = 1224
Height = 905
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 280.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Event.bf"
TabWidth = 86.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Event.bf"
CursorPos = 296
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ScrollBarVert.bf"
TabWidth = 130.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\ScrollBarVert.bf"
CursorPos = 964
VertPos = 45.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ScrollBarHoriz.bf"
TabWidth = 137.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\ScrollBarHoriz.bf"
CursorPos = 1145
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Button.bf"
TabWidth = 82.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\Button.bf"
CursorPos = 1276
VertPos = 495.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Text.bf"
TabWidth = 68.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\Text.bf"
CursorPos = 545
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Theme.bf"
TabWidth = 84.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\Theme.bf"
CursorPos = 530
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "List.bf"
TabWidth = 64.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\Beef\\BeefLibs\\corlib\\src\\Collections\\List.bf"
CursorPos = 16587
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Form.bf"
TabWidth = 75.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\MinceTest\\src\\Form.bf"
CursorPos = 441
VertPos = 90.0
ProjectName = "MinceTest"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Background.bf"
TabWidth = 114.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Background.bf"
CursorPos = 327
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Color.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Color.bf"
CursorPos = 10220
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Frame.bf"
TabWidth = 81.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Frame.bf"
CursorPos = 173
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 96.0
Type = "SourceViewPanel"
FilePath = "z:\\Development\\MinceTest\\src\\Program.bf"
CursorPos = 200
ProjectName = "MinceTest"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SDL2.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\SDL2.bf"
CursorPos = 2668
VertPos = 1215.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Window.bf"
TabWidth = 92.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\Window.bf"
CursorPos = 2238
VertPos = 945.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Panel.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "src\\Forms\\Panel.bf"
CursorPos = 1050
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Size.bf"
TabWidth = 68.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Size.bf"
CursorPos = 200
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Rect.bf"
TabWidth = 70.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Rect.bf"
CursorPos = 457
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Point.bf"
TabWidth = 74.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Point.bf"
CursorPos = 212
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Control.bf"
TabWidth = 88.0
Type = "SourceViewPanel"
FilePath = "src\\Core\\Control.bf"
CursorPos = 1879
VertPos = 945.0
ProjectName = "Mince"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 370.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4379562
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5620438
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"
